### ISSUE TITLE
Running test crashes

### ISSUE THREAD

**Issue by ostcar** [jwoudenberg/rvn#6]
When I try to run the test, roc crashes.

I called: `roc test package/Rvn.roc`

The output is:

```
thread '<unnamed>' panicked at crates/compiler/mono/src/ir/decision_tree.rs:777:17:
IntLiteral([91, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], U8)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have compiled roc from source at commit `f7011c8e33b92a7e9f809e6f16849de9fcfa8dd7`

By the way: I really like the idea of rvn. Thank you for that package

**Comment by jwoudenberg** [comment]
Hi @ostcar, thanks for the nice words, and for the bug report!

I did an upgrade to the latest version of Roc today, imagined that might explain it. But I've also got that version of Roc build, and when I run the command the tests pass for me, I don't get that error. Not sure what's up!

Could machine architecture explain the difference? I'm on `linux-86_64`, how about you?

**Comment by ostcar** [comment]
I found it.

I compiled roc with `cargo build` that creates a debug build. With that build, I get the error.

When I build a release build of roc, it works:

```
$ ~/src/roc/target/release/roc test package/Rvn.roc 
0 failed and 92 passed in 1211 ms.
$ ~/src/roc/target/debug/roc  test package/Rvn.roc 
thread '<unnamed>' panicked at crates/compiler/mono/src/ir/decision_tree.rs:777:17:
IntLiteral([91, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], U8)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So this is not a bug in your project.

Currently, I have to copy your code. Would you consider creating a release of rvg?

**Comment by jwoudenberg** [comment]
I'm glad you found it!

I created a release:
https://github.com/jwoudenberg/rvn/releases/tag/0.1.0

First time I did this, let me know if something isn't working!

**Comment by ostcar** [comment]
Thank you.

I am trying to use rvn, because I though, it could easily decode Roc-Tags. I realize now, that this is currently not possible, because of the limitation of Roc.

What do you think would be necessary to get Roc to support Tags?

**Comment by jwoudenberg** [comment]
Ah, yes. I'd love to cover tag decoding as well and would add it as soon as support lands in Roc.

My understanding is that Isaac has done a lot of work towards implementing it, and that currently no-one is working on it. This is the last I've seen on the subject on Roc Zulip:
https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/json.20null.20handling/near/408719663
